version: "3.9"

services:
  api: 
    build: . 
    command: ["api", "--host", "0.0.0.0", "--port", "8000"]
    env_file:
      - .env 
    ports:
      - "8000:8000"
    volumes:
      - "./artifacts:/app/artifacts"
    restart: unless-stopped